# Generated by Django 6.0.5 on 2026-05-06 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(help_text='The grammatical sentence to analyze')),
                ('sentence_type', models.CharField(choices=[('declarative', 'Declarative'), ('interrogative', 'Interrogative'), ('exclamative', 'Exclamative'), ('imperative', 'Imperative')], help_text='The type of sentence', max_length=20)),
                ('sentence_structure', models.CharField(choices=[('simple', 'Simple'), ('compound', 'Compound'), ('complex', 'Complex'), ('compound-complex', 'Compound-Complex')], help_text='The structure of the sentence', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional visual representation of the sentence', null=True, upload_to='sentence_diagrams/')),
                ('reed_kellogg_spec', models.JSONField(blank=True, help_text='JSON specification for Reed-Kellogg diagram', null=True)),
                ('dependency_graph_spec', models.JSONField(blank=True, help_text='JSON specification for dependency graph', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when sentence was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when sentence was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this sentence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this sentence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagramExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_type', models.CharField(choices=[('node', 'Node'), ('edge', 'Edge')], help_text='Type of diagram element (node or edge)', max_length=20)),
                ('element_id', models.CharField(help_text='Identifier for the diagram element (e.g., node ID, edge ID)', max_length=255)),
                ('explanation', models.TextField(help_text='Clarification text explaining the diagram decision')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when explanation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when explanation was last updated')),
                ('ordering_index', models.IntegerField(default=0, help_text='Order for displaying multiple explanations')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this explanation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagram_explanations_created', to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(help_text='Reference to the parent sentence', on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='api.sentence')),
            ],
            options={
                'ordering': ['sentence', 'ordering_index'],
            },
        ),
        migrations.CreateModel(
            name='SentenceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(help_text='Sequential revision number')),
                ('sentence_text', models.TextField(help_text='The sentence text at this revision')),
                ('sentence_type', models.CharField(choices=[('declarative', 'Declarative'), ('interrogative', 'Interrogative'), ('exclamative', 'Exclamative'), ('imperative', 'Imperative')], help_text='Sentence type at this revision', max_length=20)),
                ('sentence_structure', models.CharField(choices=[('simple', 'Simple'), ('compound', 'Compound'), ('complex', 'Complex'), ('compound-complex', 'Compound-Complex')], help_text='Sentence structure at this revision', max_length=20)),
                ('reed_kellogg_spec', models.JSONField(blank=True, help_text='Reed-Kellogg diagram spec at this revision', null=True)),
                ('dependency_graph_spec', models.JSONField(blank=True, help_text='Dependency graph spec at this revision', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this revision was created')),
                ('change_summary', models.TextField(blank=True, help_text='Optional description of changes in this revision')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made this revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentence_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(help_text='Reference to the parent sentence', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.sentence')),
            ],
            options={
                'ordering': ['sentence', 'revision_number'],
            },
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['created_at'], name='api_sentenc_created_c7bf90_idx'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['updated_at'], name='api_sentenc_updated_2b2ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramexplanation',
            index=models.Index(fields=['sentence', 'element_id'], name='api_diagram_sentenc_2131cc_idx'),
        ),
        migrations.AddIndex(
            model_name='diagramexplanation',
            index=models.Index(fields=['created_at'], name='api_diagram_created_f1b543_idx'),
        ),
        migrations.AddIndex(
            model_name='sentencerevision',
            index=models.Index(fields=['sentence', 'revision_number'], name='api_sentenc_sentenc_029848_idx'),
        ),
        migrations.AddIndex(
            model_name='sentencerevision',
            index=models.Index(fields=['changed_at'], name='api_sentenc_changed_4ddef2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sentencerevision',
            unique_together={('sentence', 'revision_number')},
        ),
    ]
