# Exported from Render on 2026-05-22T12:26:09Z
version: "1"
projects:
- name: GrammifyPoli Project
  environments:
  - name: Production
    services:
    - type: web
      name: GrammifyPoli
      runtime: python
      repo: https://github.com/PabloAtPoli/GrammifyPoli
      plan: free
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn backend.wsgi
      autoDeployTrigger: commit
      rootDir: backend
      envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: grammifypoli.onrender.com

        